dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
before_install:
  - pip install poetry
install:
  - rm poetry.lock # necessary because locked torch version has no linux wheel
  - poetry install -n
  - python -m laserembeddings download-models
script:
  - poetry run pylint laserembeddings
  - poetry run pytest
